version: '2'
services:

  jenkins:
    build:
      context: .
      dockerfile: DockerfileJenkins
    hostname: jenkins
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000

    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - kafka-stack-network

networks:
  kafka-stack-network:
    driver: bridge